### ISSUE TITLE
Propose adding "details" to `chunkedgraph.get_tabular_change_log()`

### ISSUE THREAD

**Issue by bdpedigo** [seung-lab/CAVEclient#126]
Some of the fields currently returned by `chunkedgraph.get_operation_details()` don't show up in the tabular change log, for instance, source/sink coords. 

I feel like this would be useful to have to get all of the information in one place.

**Comment by fcollman** [comment]
I think this is an issue for  this repo. https://www.github.com/seung-lab/pychunkedgraph

**Comment by bdpedigo** [comment]
done!
