### ISSUE TITLE
Wrong docstring in AnnotationClient.annotation.delete_annotation

### ISSUE THREAD

**Issue by schlegelp** [seung-lab/CAVEclient#51]
Hi! Not a big deal but probably slightly confusing for the less versed Pythonista:

The docstring for deleting annotations (`AnnotationClient.annotation.delete_annotation`) is the same as that for updating annotations.

https://github.com/seung-lab/CAVEclient/blob/dec850dff9e0fa0a9ef8c2a0c79bf82cd2fc5b97/caveclient/annotationengine.py#L550

**Comment by fcollman** [comment]
I think we have addressed this now!
